services:
 mysqldb:
  image: mysql:latest
  restart: unless-stopped
  environment:
  - MYSQL_DATABASE=kaddemdb
  - MYSQL_ALLOW_EMPTY_PASSWORD= 'yes'
  ports:
  - 3306:3306
  volumes:
  - db:/var/lib/mysql
 kaddem-app:
  depends_on:
  - mysqldb
  image: guesmimelek/kaddem-app:0.0.1
  restart: on-failure
  ports:
  - "8089:8089"
  environment:
   SPRING_APPLICATION_JSON: '{
   "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddemdb?createDatabaseIfNotExist=true",
   "spring.datasource.username": "root",
   "spring.datasource.password": null,
   "spring. jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
   "spring.jpa.hibernate.ddl-auto": "update"
   }'
  stdin_open: true
  tty: true

volumes:
  db :
