version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: kaddemdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - events-network


  kaddem-app:
    depends_on:
      - mysqldb
    image: ahmedbenhmida/kaddem-app:1.0.0
    container_name: kaddem-app
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddemdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_SHOW_SQL: "true"
    stdin_open: true
    tty: true

volumes:
  db:
