version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kaddemdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - events-network

  spring-boot-app:
    image: guesmimelek/kaddem-app:0.0.1
    container_name: DEVOPS
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddemdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      - events-network
    tty: true
    stdin_open: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - events-network
    command: '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  mysql-data:

networks:
  events-network:
