global:
  scrape_interval: 15s  # Set the scrape interval

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.10:8089']